
class CD:
    """
    a class containing callback data constants
    """

    CANCEL_CONV = "CANCELCONV"

    CHANNEL_SETTING = 'CS'
    ADD_CHANNEL = 'ADDCHNL'
    ACTIVATE = 'AC'
    DEACTIVATE = 'DEA'


    I_JOIN_IN_ALL = "IJIA"

    DELETE_ORDER = "APDELETEORD"
    EDIT_ORDER = "APEORD"
    ORDER_STATS = "APOSTATS"


    DL_STORIES = "DLSS"
    HIGHLIGHS_LIST = "HLL"
    DL_HIGHLIGHT = "HLD"
    DL_SINGLE_STORY = "DSS"
    


    FORCED_JOIN_FOR_SUBSCRIPTION = "FJFS"
    IS_SUBSCRIPTION_DEFAULT = "ISDS"
    SET_SUBSCRIPTION_LIMIT = "SSRL"
    PERMIT_DONWLOAD_TYPE = "PDT"
    CREATE_SUBSCRIPTION_IN_DB = "CSITD"

    SUBSCRIPTION_PLAN_INFO = "SPINFO"
    EDIT_SUBSCRIPTION_PLAN_NAME = "ESPNA"
    EDIT_SUBSCRIPTION_PLAN_LIMIT = "ESPL"
    EDIT_SET_SUBSCRIPTION_PLAN_LIMIT = "ESSPL"
    EDIT_SUBSCRIPTION_PLAN_FORCE_JOIN = "ESPFJ"
    EDIT_SET_SUBSCRIPTION_PLAN_FORCE_JOIN = "ESSPFJ"
    EDIT_SUBSCRIPTION_PLAN_DEFAULTNESS = "ESPDN"
    EDIT_SET_SUBSCRIPTION_PLAN_DEFAULTNESS = "ESSPDN"


    STATISTICS = "STATS"
    REFERRAL_STATISTICS = "REFSTATS"
    API_STATS = "APISTATS"
    API_HEALTH_STATS = "APIHS"
    REQUEST_TYPE_STATS = "RTSTATS"
    STATS_CHARTS = "STSCHARTS"
    LOYALTY_STATS = "LOYALTYSTS"


    ADDING_NEW_MESSAGE = "ANMTDB"
    LISTING_MESSAGES = "LISTMSGS"

    ADDING_NEW_SOURCE_LINK = "ANSLS"
    LISTING_SOURCE_LINKS = "LISTSLS"
    
    ADDING_NEW_COMMAND = "ANCMND"
    LISTING_COMMANDS = "LCMNDS"
    COMMAND_INFO = "CMNDINFO"
    COMMAND_MESSAGES_MANAGEMENT = "CMNDMMM"
    DELETE_COMMAND = "DELCMND"
    DELETE_COMMAND_MESSAGE = "DELCMNDMSG"
    ADD_COMMAND_MESSAGE = "ADCMNDMSG"
    ADD_COMMAND_MESSAGE_TO_DB = "ADDCMTDB"
    
    LIST_BROADCASTS = "LISTBC"
    BROADCAST_INFO = "BCINFO"

    TOGGLE_BROADCASTING = "TBCSTING" #START/PAUSE
    SHOW_DB_MESSAGE = "SHDBMSG"
    SHOW_BROADCAST_MESSAGE = "SHBCMSG"

    ADD_NEW_BROADCAST = "ADDNBC"
    SET_BROADCAST_MESSAGE = "SBM"
    SET_BROADCAST_RATE = "SBR"
    SET_BROADCAST_COVERAGE = "SBCGE"

    CHANNEL_INFO = "CHNLINFO"
    CHANNEL_DELETE = "CHNLDEL"
    CHANNEL_DELETE_CONFIRMED = "CHNDELCONFIRM"
    CHANNEL_TOGGLE_TRACKING = "CHNLTGLTRACKING"
    CHANNEL_ACCEPTER_MESSAGE_MANAGEMENT = "CHNLACCEPTERMSGMNG"
    CHANNEL_SET_ACCEPTER_MSG = "CHNSAN"

    DO_NOTHING = "DONOTHING"

    NEW_BTN = "NBTN"
    CHOOSE_BTN_TYPE = "BTN_TYPE"

    CHOOSE_BTN_MESSAGE = "CHBTNMSG"
    CREATE_BTN = "CRBTN"
    CHOOSE_BTN_TYPE = "CHBTNT"


    INCREASE_BALANCE = "IBALANCE"

    GET_REFERRAL_LINK = "GREFERRALLINK"