class CONV():

    GET_ORDER_TYPE = "OTYPE" #FAKE OR NOT
    GET_ORDER_TITLE = "OTITLE"

    GET_ORDER_MEMBER_TRAKING_TYPE = "OMT"
    GET_ORDER_NUMBER_OF_MEMBERS = "ONOM"
    GET_ORDER_LINK = "OLINK"
    SET_CHANNEL_INFO = "OSCI"
    IS_AUTO_GENERATED_LINK = "ILATG"

    CHOOSE_MESSAGE_ID = "CMID"
    GET_RATE = "GETBCRATE"
    USERS_TO_BE_SENT_TO = "UTBST"

    GETTING_A_NEW_MESSAGE = "GANM"
    GETTING_A_NEW_COMMAND = "GNACMND"

    SET_BTN_TITLE = "SETBTNTITLE"
    SET_BTN_LINK = "SETBTNLINK"
    SET_BTN_TYPE = "SETBTNTYPE"

    GET_CHANNEL_MSG = "GETCHNLMSG"
    
class SUBP():
    SET_NAME="SSPN"